[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.1.2" }

[package.metadata.risc0]
methods = ["guest"]

[dependencies]
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }

